### ISSUE TITLE
AttributeError: 'coo_matrix' object has no attribute 'A'

### ISSUE THREAD

**Issue by michguo** [zfergus/seam-erasure#8]
I am getting the error after "Building Least Squares Constraints". The command I am running is 

```
seam-erasure path/to/input_model path/to/input_texture
```

Error: 

```
AttributeError: 'coo_matrix' object has no attribute 'A'
```

**Comment by zfergus** [comment]
I think Scipy removed `.A` at some point. You can change it to `.toarray()` and try again.
